# Generated by Django 4.2 on 2023-04-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
